baseurl = "https://tgjeon.github.io/"
title = "Taegyun Jeon"
copyright = "&copy; 2016 Taegyun Jeon"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
disqusShortname = "vuscon"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""


[params]
    name = "Taegyun Jeon"
    role = "Research Scientist in Machine Learning and Biomedical Engineering"
    organization = "Gwangju Institute of Science & Technology"
    interests = ["Biomedical Signal Processing", "Deep Learning", "Embedded Systems"]
    email = "tgjeon@gist.ac.kr"
    address = "Machine Learning and Vision Lab, Gwangju Institute of Science and Technology, Gwangju, South Korea."
    phone = "+82 62 715 2633"

    # Date format (refer to Go's date format: http://flippinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "Mon, Jan 2, 2006"

    # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
    math = false

    # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
    custom_css = []
    custom_js  = []

    [[params.education]]
        course = "PhD in Biomedical Signal Analysis"
        institution = "Gwangju Institute of Science and Technology"
        year = 2016

    [[params.education]]
        course = "MSc in Machine Learning"
        institution = "Gwangju Institute of Science and Technology"
        year = 2009

    [[params.education]]
        course = "BEng in Computer Engineering"
        institution = "Dong-A University"
        year = 2007

    [params.contact]
        # Automatically link email and phone?
        autolink = true

    # Social/Academic Networking
    #
    # Icon pack "fa" includes the following social network icons:
    #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
    #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
    #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
    #
    # Icon pack "ai" includes the following academic network icons:
    #   google-scholar, arxiv, orcid, researchgate, mendeley
    #   Full list: https://jpswalsh.github.io/academicons/

    [[params.social]]
        icon = "envelope"
        icon_pack = "fa"
        link = "mailto:tgjeon@gist.ac.kr"

    [[params.social]]
        icon = "linkedin"
        icon_pack = "fa"
        link = "//linkedin.com/in/tgjeon"

    [[params.social]]
        icon = "google-scholar"
        icon_pack = "ai"
        link = "https://scholar.google.co.kr/citations?user=tOzFCbIAAAAJ&hl=en"

    [[params.social]]
        icon = "github"
        icon_pack = "fa"
        link = "//github.com/tgjeon"


    # Navigation Links
    #
    # The weight parameter defines the order that the links will appear in.

[[menu.main]]
    name = "Home"
    url = "#top"
    weight = 1

[[menu.main]]
    name = "Publications"
    url = "#publications"
    weight = 2

[[menu.main]]
    name = "Posts"
    url = "#posts"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 6
